name: Generate Pacman Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate-pacman-from-github-contribution-grid
        uses: lowlighter/metrics@latest
        with:
          filename: github-pacman.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: no
          plugin_animations: yes
          plugin_animations_format: svg
          # Mengaktifkan mode pacman khusus kontribusi
          config_order: pacman
